[2024-11-25T15:51:10.085+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [queued]>
[2024-11-25T15:51:10.090+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [queued]>
[2024-11-25T15:51:10.091+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-11-25T15:51:10.100+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-25 15:50:54.302443+00:00
[2024-11-25T15:51:10.110+0000] {standard_task_runner.py:60} INFO - Started process 731 to run task
[2024-11-25T15:51:10.113+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_project', 'train_model', 'manual__2024-11-25T15:50:54.302443+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/ml_project.py', '--cfg-path', '/tmp/tmpke4mtlnu']
[2024-11-25T15:51:10.115+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask train_model
[2024-11-25T15:51:10.150+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [running]> on host e084ca88f62c
[2024-11-25T15:51:10.201+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_project' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T15:50:54.302443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T15:50:54.302443+00:00'
[2024-11-25T15:51:10.206+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:51:14.257+0000] {logging_mixin.py:188} WARNING - Downloading builder script:   0%|          | 0.00/4.20k [00:00<?, ?B/s]
[2024-11-25T15:51:14.258+0000] {logging_mixin.py:188} WARNING - Downloading builder script: 100%|##########| 4.20k/4.20k [00:00<00:00, 16.9MB/s]
[2024-11-25T15:51:14.928+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/35000 [00:00<?, ? examples/s]
[2024-11-25T15:51:26.965+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:12<00:00, 2907.89 examples/s]
[2024-11-25T15:51:27.235+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:12<00:00, 2844.24 examples/s]
[2024-11-25T15:51:27.258+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/15000 [00:00<?, ? examples/s]
[2024-11-25T15:51:30.129+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:02<00:00, 5246.59 examples/s]
[2024-11-25T15:51:30.187+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:02<00:00, 5143.29 examples/s]
[2024-11-25T15:51:30.189+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:51:32.260+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/train_model.py", line 52, in train_model
    args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'
[2024-11-25T15:51:32.267+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_project, task_id=train_model, execution_date=20241125T155054, start_date=20241125T155110, end_date=20241125T155132
[2024-11-25T15:51:32.277+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task train_model (TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'; 731)
[2024-11-25T15:51:32.495+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-25T15:51:32.512+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
