[2024-11-25T15:54:00.962+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [queued]>
[2024-11-25T15:54:00.968+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [queued]>
[2024-11-25T15:54:00.969+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-11-25T15:54:00.980+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-25 15:50:54.302443+00:00
[2024-11-25T15:54:00.992+0000] {standard_task_runner.py:60} INFO - Started process 1096 to run task
[2024-11-25T15:54:00.994+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_project', 'train_model', 'manual__2024-11-25T15:50:54.302443+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/ml_project.py', '--cfg-path', '/tmp/tmpx5u_9znp']
[2024-11-25T15:54:00.996+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask train_model
[2024-11-25T15:54:01.031+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [running]> on host e084ca88f62c
[2024-11-25T15:54:01.082+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_project' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T15:50:54.302443+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T15:50:54.302443+00:00'
[2024-11-25T15:54:01.088+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:54:03.767+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/35000 [00:00<?, ? examples/s]
[2024-11-25T15:54:15.487+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:11<00:00, 2986.47 examples/s]
[2024-11-25T15:54:15.618+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:11<00:00, 2953.55 examples/s]
[2024-11-25T15:54:15.625+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/15000 [00:00<?, ? examples/s]
[2024-11-25T15:54:18.554+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:02<00:00, 5122.19 examples/s]
[2024-11-25T15:54:18.613+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:02<00:00, 5021.29 examples/s]
[2024-11-25T15:54:18.615+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:54:18.950+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/train_model.py", line 52, in train_model
    args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'
[2024-11-25T15:54:18.956+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_project, task_id=train_model, execution_date=20241125T155054, start_date=20241125T155400, end_date=20241125T155418
[2024-11-25T15:54:18.967+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task train_model (TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'; 1096)
[2024-11-25T15:54:19.164+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-25T15:54:19.180+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
