[2024-11-25T15:52:37.024+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [queued]>
[2024-11-25T15:52:37.029+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [queued]>
[2024-11-25T15:52:37.029+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-11-25T15:52:37.039+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-25 15:50:54.302443+00:00
[2024-11-25T15:52:37.053+0000] {standard_task_runner.py:60} INFO - Started process 914 to run task
[2024-11-25T15:52:37.055+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_project', 'train_model', 'manual__2024-11-25T15:50:54.302443+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ml_project.py', '--cfg-path', '/tmp/tmpjlay1391']
[2024-11-25T15:52:37.057+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask train_model
[2024-11-25T15:52:37.092+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_project.train_model manual__2024-11-25T15:50:54.302443+00:00 [running]> on host e084ca88f62c
[2024-11-25T15:52:37.150+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_project' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T15:50:54.302443+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-25T15:50:54.302443+00:00'
[2024-11-25T15:52:37.156+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:52:39.833+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/35000 [00:00<?, ? examples/s]
[2024-11-25T15:52:51.693+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:11<00:00, 2951.46 examples/s]
[2024-11-25T15:52:51.820+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:11<00:00, 2920.27 examples/s]
[2024-11-25T15:52:51.828+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/15000 [00:00<?, ? examples/s]
[2024-11-25T15:52:55.323+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:03<00:00, 4293.06 examples/s]
[2024-11-25T15:52:55.382+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:03<00:00, 4221.71 examples/s]
[2024-11-25T15:52:55.384+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:52:55.716+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/train_model.py", line 52, in train_model
    args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'
[2024-11-25T15:52:55.722+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_project, task_id=train_model, execution_date=20241125T155054, start_date=20241125T155237, end_date=20241125T155255
[2024-11-25T15:52:55.742+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task train_model (TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'; 914)
[2024-11-25T15:52:55.976+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-25T15:52:55.993+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
