[2024-11-25T15:54:00.992+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_project.train_model scheduled__2024-11-24T00:00:00+00:00 [queued]>
[2024-11-25T15:54:00.997+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_project.train_model scheduled__2024-11-24T00:00:00+00:00 [queued]>
[2024-11-25T15:54:00.998+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2024-11-25T15:54:01.008+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2024-11-24 00:00:00+00:00
[2024-11-25T15:54:01.019+0000] {standard_task_runner.py:60} INFO - Started process 1097 to run task
[2024-11-25T15:54:01.021+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_project', 'train_model', 'scheduled__2024-11-24T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/ml_project.py', '--cfg-path', '/tmp/tmpavu14en5']
[2024-11-25T15:54:01.023+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask train_model
[2024-11-25T15:54:01.056+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_project.train_model scheduled__2024-11-24T00:00:00+00:00 [running]> on host e084ca88f62c
[2024-11-25T15:54:01.109+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_project' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-24T00:00:00+00:00'
[2024-11-25T15:54:01.114+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:54:04.708+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/35000 [00:00<?, ? examples/s]
[2024-11-25T15:54:16.951+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:12<00:00, 2858.82 examples/s]
[2024-11-25T15:54:17.081+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 35000/35000 [00:12<00:00, 2828.93 examples/s]
[2024-11-25T15:54:17.088+0000] {logging_mixin.py:188} WARNING - Map:   0%|          | 0/15000 [00:00<?, ? examples/s]
[2024-11-25T15:54:19.584+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:02<00:00, 6010.11 examples/s]
[2024-11-25T15:54:19.642+0000] {logging_mixin.py:188} WARNING - Map: 100%|##########| 15000/15000 [00:02<00:00, 5874.88 examples/s]
[2024-11-25T15:54:19.643+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py:797 FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
[2024-11-25T15:54:19.940+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/train_model.py", line 52, in train_model
    args = TrainingArguments(
TypeError: TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'
[2024-11-25T15:54:19.947+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_project, task_id=train_model, execution_date=20241124T000000, start_date=20241125T155400, end_date=20241125T155419
[2024-11-25T15:54:19.959+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task train_model (TrainingArguments.__init__() got an unexpected keyword argument 'eval_strategy'; 1097)
[2024-11-25T15:54:20.133+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-25T15:54:20.148+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
